# Modifying DataFrames

We will use the same data as we used before, [federal support to all Canadian Provinces and Territories](https://www.fin.gc.ca/fedprov/mtp-eng.asp) :

In [2]:
import pandas as pd
import numpy as np

prov_support = pd.read_csv('pandas_ex1.csv',
                           sep=',',
                           skiprows=1,  # skipping one row
                           header=None, # Set to None, since we are skipping the first row
                           names= ['province_name','province','2016','2017','2018'], # names of columns
                           index_col= 'province') # use column 'province' as the index

prov_support

C:\Users\meddi\AppData\Local\Temp\ipykernel_24152\2101985344.py:1: DeprecationWarning: 
Pyarrow will become a required dependency of pandas in the next major release of pandas (pandas 3.0),
(to allow more performant data types, such as the Arrow string type, and better interoperability with other libraries)
but was not found to be installed on your system.
If this would cause problems for you,
please provide us feedback at https://github.com/pandas-dev/pandas/issues/54466
        
  import pandas as pd


province_name   2016   2017   2018
province                                                
NL        Newfoundland and Labrador    724    734    750
PE             Prince Edward Island    584    601    638
NS                      Nova Scotia   3060   3138   3201
NB                    New Brunswick   2741   2814   2956
QC                           Quebec  21372  22720  23749
ON                          Ontario  21347  21101  21420
MB                         Manitoba   3531   3675   3965
SK                     Saskatchewan   1565   1613   1673
AB                          Alberta   5772   5943   6157
BC                 British Columbia   6482   6680   6925
YT                            Yukon    946    973   1006
NT            Northwest Territories   1281   1294   1319
NU                          Nunavut   1539   1583   1634

## Add a column

In [3]:
# Create a new column '2016-2018 change'. The new column is always added to the right
prov_support['2016-2018 change'] = prov_support['2018'] - prov_support['2016']

prov_support

province_name   2016   2017   2018  2016-2018 change
province                                                                  
NL        Newfoundland and Labrador    724    734    750                26
PE             Prince Edward Island    584    601    638                54
NS                      Nova Scotia   3060   3138   3201               141
NB                    New Brunswick   2741   2814   2956               215
QC                           Quebec  21372  22720  23749              2377
ON                          Ontario  21347  21101  21420                73
MB                         Manitoba   3531   3675   3965               434
SK                     Saskatchewan   1565   1613   1673               108
AB                          Alberta   5772   5943   6157               385
BC                 British Columbia   6482   6680   6925               443
YT                            Yukon    946    973   1006                60
NT            Northwest Territories   1281   1294   1319                38
NU                          Nunavut   1539   1583   1634                95

## Update a value

In [4]:
#  update the '2017' value for Ontario from 21101 to 22222
prov_support.loc['ON', '2017'] = 22222

prov_support

province_name   2016   2017   2018  2016-2018 change
province                                                                  
NL        Newfoundland and Labrador    724    734    750                26
PE             Prince Edward Island    584    601    638                54
NS                      Nova Scotia   3060   3138   3201               141
NB                    New Brunswick   2741   2814   2956               215
QC                           Quebec  21372  22720  23749              2377
ON                          Ontario  21347  22222  21420                73
MB                         Manitoba   3531   3675   3965               434
SK                     Saskatchewan   1565   1613   1673               108
AB                          Alberta   5772   5943   6157               385
BC                 British Columbia   6482   6680   6925               443
YT                            Yukon    946    973   1006                60
NT            Northwest Territories   1281   1294   1319                38
NU                          Nunavut   1539   1583   1634                95

at[ ]

We can get the same result by using the at[] field which provides access to a single value. We will now change the value of 22222 back to 21101 for Ontario in 2017:

In [5]:
# get value of a cell
prov_support.at['ON', '2017']

22222

In [6]:
# set value of a data point back to 21101:
prov_support.at['ON', '2017'] = 21101

prov_support

province_name   2016   2017   2018  2016-2018 change
province                                                                  
NL        Newfoundland and Labrador    724    734    750                26
PE             Prince Edward Island    584    601    638                54
NS                      Nova Scotia   3060   3138   3201               141
NB                    New Brunswick   2741   2814   2956               215
QC                           Quebec  21372  22720  23749              2377
ON                          Ontario  21347  21101  21420                73
MB                         Manitoba   3531   3675   3965               434
SK                     Saskatchewan   1565   1613   1673               108
AB                          Alberta   5772   5943   6157               385
BC                 British Columbia   6482   6680   6925               443
YT                            Yukon    946    973   1006                60
NT            Northwest Territories   1281   1294   1319                38
NU                          Nunavut   1539   1583   1634                95

## Delete a row or column

drop( )

In [7]:
# Deleting column '2016':
prov_support.drop('2016', axis=1) 

# *returns a copy of the DataFrame with '2016' removed

province_name   2017   2018  2016-2018 change
province                                                           
NL        Newfoundland and Labrador    734    750                26
PE             Prince Edward Island    601    638                54
NS                      Nova Scotia   3138   3201               141
NB                    New Brunswick   2814   2956               215
QC                           Quebec  22720  23749              2377
ON                          Ontario  21101  21420                73
MB                         Manitoba   3675   3965               434
SK                     Saskatchewan   1613   1673               108
AB                          Alberta   5943   6157               385
BC                 British Columbia   6680   6925               443
YT                            Yukon    973   1006                60
NT            Northwest Territories   1294   1319                38
NU                          Nunavut   1583   1634                95

In [8]:
# Deleting Ontario and Quebec from the DataFrame:
prov_support.drop(['ON', 'QC']) # axis=0 is the default parameter

province_name  2016  2017  2018  2016-2018 change
province                                                               
NL        Newfoundland and Labrador   724   734   750                26
PE             Prince Edward Island   584   601   638                54
NS                      Nova Scotia  3060  3138  3201               141
NB                    New Brunswick  2741  2814  2956               215
MB                         Manitoba  3531  3675  3965               434
SK                     Saskatchewan  1565  1613  1673               108
AB                          Alberta  5772  5943  6157               385
BC                 British Columbia  6482  6680  6925               443
YT                            Yukon   946   973  1006                60
NT            Northwest Territories  1281  1294  1319                38
NU                          Nunavut  1539  1583  1634                95

When then drop() function is called, pandas creates a new DataFrame object, the original DataFrame is not modified. If we need to modify the original DataFrame, then we need to set a parameter inplace = True:

In [9]:
prov_support.drop('2016', axis=1, inplace= True)

In [10]:
prov_support

province_name   2017   2018  2016-2018 change
province                                                           
NL        Newfoundland and Labrador    734    750                26
PE             Prince Edward Island    601    638                54
NS                      Nova Scotia   3138   3201               141
NB                    New Brunswick   2814   2956               215
QC                           Quebec  22720  23749              2377
ON                          Ontario  21101  21420                73
MB                         Manitoba   3675   3965               434
SK                     Saskatchewan   1613   1673               108
AB                          Alberta   5943   6157               385
BC                 British Columbia   6680   6925               443
YT                            Yukon    973   1006                60
NT            Northwest Territories   1294   1319                38
NU                          Nunavut   1583   1634                95

# Applying functions

Here is the DataFrame that we start with:

In [11]:
prov_support

province_name   2017   2018  2016-2018 change
province                                                           
NL        Newfoundland and Labrador    734    750                26
PE             Prince Edward Island    601    638                54
NS                      Nova Scotia   3138   3201               141
NB                    New Brunswick   2814   2956               215
QC                           Quebec  22720  23749              2377
ON                          Ontario  21101  21420                73
MB                         Manitoba   3675   3965               434
SK                     Saskatchewan   1613   1673               108
AB                          Alberta   5943   6157               385
BC                 British Columbia   6680   6925               443
YT                            Yukon    973   1006                60
NT            Northwest Territories   1294   1319                38
NU                          Nunavut   1583   1634                95

## .apply( )

In [12]:
# Defining a custom function to calculate the percent change:
def percent_change(years):
    yr2017, yr2018 = years
    return (yr2018 - yr2017)/yr2017 * 100

In [13]:
prov_support[['2017', '2018']].apply(percent_change, axis=1)


# axis parameter is for the axis along which the function is applided


# For example, for the row corresponding to Ontario:

# The values in the '2017' and '2018' columns are 21101 and 21420, respectively.
# These values are passed to the percent_change function as a tuple (21101, 21420)

province
NL    2.179837
PE    6.156406
NS    2.007648
NB    5.046198
QC    4.529049
ON    1.511777
MB    7.891156
SK    3.719777
AB    3.600875
BC    3.667665
YT    3.391572
NT    1.931994
NU    3.221731
dtype: float64

In [14]:
# # Create a new column for the values calculated above and add it to the DataFrame
prov_support['per_change'] = prov_support[['2017', '2018']].apply(percent_change, axis=1)
prov_support

province_name   2017   2018  2016-2018 change  \
province                                                              
NL        Newfoundland and Labrador    734    750                26   
PE             Prince Edward Island    601    638                54   
NS                      Nova Scotia   3138   3201               141   
NB                    New Brunswick   2814   2956               215   
QC                           Quebec  22720  23749              2377   
ON                          Ontario  21101  21420                73   
MB                         Manitoba   3675   3965               434   
SK                     Saskatchewan   1613   1673               108   
AB                          Alberta   5943   6157               385   
BC                 British Columbia   6680   6925               443   
YT                            Yukon    973   1006                60   
NT            Northwest Territories   1294   1319                38   
NU                          Nunavut   1583   1634                95   

          per_change  
province              
NL          2.179837  
PE          6.156406  
NS          2.007648  
NB          5.046198  
QC          4.529049  
ON          1.511777  
MB          7.891156  
SK          3.719777  
AB          3.600875  
BC          3.667665  
YT          3.391572  
NT          1.931994  
NU          3.221731

## map( )

Format all number columns as floating point numbers. We can also use the lambda function for this operation:

In [15]:

#! depcricated prov_support.loc[:, '2017':'per_change'].applymap(lambda x: '%.2f' %x) applymap() is depricated
prov_support.loc[:, '2017':'per_change'].map(lambda x: '%.2f' %x)

2017      2018 2016-2018 change per_change
province                                                
NL          734.00    750.00            26.00       2.18
PE          601.00    638.00            54.00       6.16
NS         3138.00   3201.00           141.00       2.01
NB         2814.00   2956.00           215.00       5.05
QC        22720.00  23749.00          2377.00       4.53
ON        21101.00  21420.00            73.00       1.51
MB         3675.00   3965.00           434.00       7.89
SK         1613.00   1673.00           108.00       3.72
AB         5943.00   6157.00           385.00       3.60
BC         6680.00   6925.00           443.00       3.67
YT          973.00   1006.00            60.00       3.39
NT         1294.00   1319.00            38.00       1.93
NU         1583.00   1634.00            95.00       3.22

In [16]:
prov_support['per_change'].map(lambda x: '%.2f' %x)

province
NL    2.18
PE    6.16
NS    2.01
NB    5.05
QC    4.53
ON    1.51
MB    7.89
SK    3.72
AB    3.60
BC    3.67
YT    3.39
NT    1.93
NU    3.22
Name: per_change, dtype: object

In [17]:
'''
Since applymap() is depricated, it might be better to just use map() 
whether applying a function to single column/row or multiple columns/rows
'''

'\nSince applymap() is depricated, it might be better to just use map() \nwhether applying a function to single column/row or multiple columns/rows\n'

# Sort a DataFrame

We can sort values in the DataFrame by values in a column or by index.

sort_values( )

In [18]:
# sort the values by the full name of the province i.e province_name

prov_support.sort_values('province_name')

province_name   2017   2018  2016-2018 change  \
province                                                              
AB                          Alberta   5943   6157               385   
BC                 British Columbia   6680   6925               443   
MB                         Manitoba   3675   3965               434   
NB                    New Brunswick   2814   2956               215   
NL        Newfoundland and Labrador    734    750                26   
NT            Northwest Territories   1294   1319                38   
NS                      Nova Scotia   3138   3201               141   
NU                          Nunavut   1583   1634                95   
ON                          Ontario  21101  21420                73   
PE             Prince Edward Island    601    638                54   
QC                           Quebec  22720  23749              2377   
SK                     Saskatchewan   1613   1673               108   
YT                            Yukon    973   1006                60   

          per_change  
province              
AB          3.600875  
BC          3.667665  
MB          7.891156  
NB          5.046198  
NL          2.179837  
NT          1.931994  
NS          2.007648  
NU          3.221731  
ON          1.511777  
PE          6.156406  
QC          4.529049  
SK          3.719777  
YT          3.391572

In [19]:
# descending order
prov_support.sort_values('province_name', ascending=False)

province_name   2017   2018  2016-2018 change  \
province                                                              
YT                            Yukon    973   1006                60   
SK                     Saskatchewan   1613   1673               108   
QC                           Quebec  22720  23749              2377   
PE             Prince Edward Island    601    638                54   
ON                          Ontario  21101  21420                73   
NU                          Nunavut   1583   1634                95   
NS                      Nova Scotia   3138   3201               141   
NT            Northwest Territories   1294   1319                38   
NL        Newfoundland and Labrador    734    750                26   
NB                    New Brunswick   2814   2956               215   
MB                         Manitoba   3675   3965               434   
BC                 British Columbia   6680   6925               443   
AB                          Alberta   5943   6157               385   

          per_change  
province              
YT          3.391572  
SK          3.719777  
QC          4.529049  
PE          6.156406  
ON          1.511777  
NU          3.221731  
NS          2.007648  
NT          1.931994  
NL          2.179837  
NB          5.046198  
MB          7.891156  
BC          3.667665  
AB          3.600875

sort_index( )

In [20]:
prov_support.sort_index()

province_name   2017   2018  2016-2018 change  \
province                                                              
AB                          Alberta   5943   6157               385   
BC                 British Columbia   6680   6925               443   
MB                         Manitoba   3675   3965               434   
NB                    New Brunswick   2814   2956               215   
NL        Newfoundland and Labrador    734    750                26   
NS                      Nova Scotia   3138   3201               141   
NT            Northwest Territories   1294   1319                38   
NU                          Nunavut   1583   1634                95   
ON                          Ontario  21101  21420                73   
PE             Prince Edward Island    601    638                54   
QC                           Quebec  22720  23749              2377   
SK                     Saskatchewan   1613   1673               108   
YT                            Yukon    973   1006                60   

          per_change  
province              
AB          3.600875  
BC          3.667665  
MB          7.891156  
NB          5.046198  
NL          2.179837  
NS          2.007648  
NT          1.931994  
NU          3.221731  
ON          1.511777  
PE          6.156406  
QC          4.529049  
SK          3.719777  
YT          3.391572

In [21]:
prov_support.sort_index(axis=1) # qn explain?

2016-2018 change   2017   2018  per_change  \
province                                               
NL                      26    734    750    2.179837   
PE                      54    601    638    6.156406   
NS                     141   3138   3201    2.007648   
NB                     215   2814   2956    5.046198   
QC                    2377  22720  23749    4.529049   
ON                      73  21101  21420    1.511777   
MB                     434   3675   3965    7.891156   
SK                     108   1613   1673    3.719777   
AB                     385   5943   6157    3.600875   
BC                     443   6680   6925    3.667665   
YT                      60    973   1006    3.391572   
NT                      38   1294   1319    1.931994   
NU                      95   1583   1634    3.221731   

                      province_name  
province                             
NL        Newfoundland and Labrador  
PE             Prince Edward Island  
NS                      Nova Scotia  
NB                    New Brunswick  
QC                           Quebec  
ON                          Ontario  
MB                         Manitoba  
SK                     Saskatchewan  
AB                          Alberta  
BC                 British Columbia  
YT                            Yukon  
NT            Northwest Territories  
NU                          Nunavut

# groupby( )

In [22]:
# Load 'iris.data' into a pandas DataFrame named 'iris'

iris = pd.read_csv('iris.data', sep=',',
                   header=None, # the data file does not contain a header
                   names=['sepal length','sepal width','petal length','petal width','class']) # names of columns

iris.head()

sepal length  sepal width  petal length  petal width        class
0           5.1          3.5           1.4          0.2  Iris-setosa
1           4.9          3.0           1.4          0.2  Iris-setosa
2           4.7          3.2           1.3          0.2  Iris-setosa
3           4.6          3.1           1.5          0.2  Iris-setosa
4           5.0          3.6           1.4          0.2  Iris-setosa

In [23]:
iris.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   sepal length  150 non-null    float64
 1   sepal width   150 non-null    float64
 2   petal length  150 non-null    float64
 3   petal width   150 non-null    float64
 4   class         150 non-null    object 
dtypes: float64(4), object(1)
memory usage: 6.0+ KB


In [24]:
iris.groupby('class') # group DataFrame by the values in the 'class' column


# the result is a GroupBy object.
# By default, the groupby() groups on axis=0.

groupby( ) does not alter your original DataFrame. It simply creates a groupby object that organizes the data based on the grouping you specify. 

.groups

The .groups attribute of a pandas GroupBy object returns a dictionary where the keys are the groups (in this case, the unique values of the grouping column 'class') and the values are arrays of the indices corresponding to the rows in the original DataFrame that belong to each group.

In [25]:
iris_grouped = iris.groupby('class') # create a new variable for the groupby object

iris_grouped.groups 

{'Iris-setosa': [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49], 'Iris-versicolor': [50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99], 'Iris-virginica': [100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149]}

In [26]:
# return a DataFrame of a single group
iris_grouped.get_group('Iris-versicolor')

sepal length  sepal width  petal length  petal width            class
50           7.0          3.2           4.7          1.4  Iris-versicolor
51           6.4          3.2           4.5          1.5  Iris-versicolor
52           6.9          3.1           4.9          1.5  Iris-versicolor
53           5.5          2.3           4.0          1.3  Iris-versicolor
54           6.5          2.8           4.6          1.5  Iris-versicolor
55           5.7          2.8           4.5          1.3  Iris-versicolor
56           6.3          3.3           4.7          1.6  Iris-versicolor
57           4.9          2.4           3.3          1.0  Iris-versicolor
58           6.6          2.9           4.6          1.3  Iris-versicolor
59           5.2          2.7           3.9          1.4  Iris-versicolor
60           5.0          2.0           3.5          1.0  Iris-versicolor
61           5.9          3.0           4.2          1.5  Iris-versicolor
62           6.0          2.2           4.0          1.0  Iris-versicolor
63           6.1          2.9           4.7          1.4  Iris-versicolor
64           5.6          2.9           3.6          1.3  Iris-versicolor
65           6.7          3.1           4.4          1.4  Iris-versicolor
66           5.6          3.0           4.5          1.5  Iris-versicolor
67           5.8          2.7           4.1          1.0  Iris-versicolor
68           6.2          2.2           4.5          1.5  Iris-versicolor
69           5.6          2.5           3.9          1.1  Iris-versicolor
70           5.9          3.2           4.8          1.8  Iris-versicolor
71           6.1          2.8           4.0          1.3  Iris-versicolor
72           6.3          2.5           4.9          1.5  Iris-versicolor
73           6.1          2.8           4.7          1.2  Iris-versicolor
74           6.4          2.9           4.3          1.3  Iris-versicolor
75           6.6          3.0           4.4          1.4  Iris-versicolor
76           6.8          2.8           4.8          1.4  Iris-versicolor
77           6.7          3.0           5.0          1.7  Iris-versicolor
78           6.0          2.9           4.5          1.5  Iris-versicolor
79           5.7          2.6           3.5          1.0  Iris-versicolor
80           5.5          2.4           3.8          1.1  Iris-versicolor
81           5.5          2.4           3.7          1.0  Iris-versicolor
82           5.8          2.7           3.9          1.2  Iris-versicolor
83           6.0          2.7           5.1          1.6  Iris-versicolor
84           5.4          3.0           4.5          1.5  Iris-versicolor
85           6.0          3.4           4.5          1.6  Iris-versicolor
86           6.7          3.1           4.7          1.5  Iris-versicolor
87           6.3          2.3           4.4          1.3  Iris-versicolor
88           5.6          3.0           4.1          1.3  Iris-versicolor
89           5.5          2.5           4.0          1.3  Iris-versicolor
90           5.5          2.6           4.4          1.2  Iris-versicolor
91           6.1          3.0           4.6          1.4  Iris-versicolor
92           5.8          2.6           4.0          1.2  Iris-versicolor
93           5.0          2.3           3.3          1.0  Iris-versicolor
94           5.6          2.7           4.2          1.3  Iris-versicolor
95           5.7          3.0           4.2          1.2  Iris-versicolor
96           5.7          2.9           4.2          1.3  Iris-versicolor
97           6.2          2.9           4.3          1.3  Iris-versicolor
98           5.1          2.5           3.0          1.1  Iris-versicolor
99           5.7          2.8           4.1          1.3  Iris-versicolor

# Aggregation .mean( )

Now we can select an aggregate function to apply to each group in the GroupBy object. For example, we can compute the mean for each column within each group:

In [27]:
iris_grouped.mean()

sepal length  sepal width  petal length  petal width
class                                                                
Iris-setosa             5.006        3.418         1.464        0.244
Iris-versicolor         5.936        2.770         4.260        1.326
Iris-virginica          6.588        2.974         5.552        2.026

In [28]:
iris_grouped.median()

sepal length  sepal width  petal length  petal width
class                                                                
Iris-setosa               5.0          3.4          1.50          0.2
Iris-versicolor           5.9          2.8          4.35          1.3
Iris-virginica            6.5          3.0          5.55          2.0

.idxmax( )

In [30]:
iris['petal length'].idxmax()

118

In [31]:
def longest_petal(g):
    return g.loc[g['petal length'].idxmax()]

iris_grouped.apply(longest_petal)

C:\Users\meddi\AppData\Local\Temp\ipykernel_24152\2882325453.py:4: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  iris_grouped.apply(longest_petal)


sepal length  sepal width  petal length  petal width  \
class                                                                   
Iris-setosa               4.8          3.4           1.9          0.2   
Iris-versicolor           6.0          2.7           5.1          1.6   
Iris-virginica            7.7          2.6           6.9          2.3   

                           class  
class                             
Iris-setosa          Iris-setosa  
Iris-versicolor  Iris-versicolor  
Iris-virginica    Iris-virginica

We can select a particular column from the original DataFrame while grouping:

In [32]:
iris.groupby('class')['petal length'].mean() # returns a series object

class
Iris-setosa        1.464
Iris-versicolor    4.260
Iris-virginica     5.552
Name: petal length, dtype: float64

.aggregate( )

Pandas GroupBy also allows us to compute multiple aggregate functions. For example, we can calculate min(), max() and mean() for 'petal length' and 'sepal length', for each group of flowers based on the flower class:

In [39]:
iris.groupby('class')[['petal length','sepal length']].aggregate(['min', np.mean, max])

C:\Users\meddi\AppData\Local\Temp\ipykernel_24152\1562241556.py:1: FutureWarning: The provided callable <function mean at 0x000001DCB738A020> is currently using SeriesGroupBy.mean. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "mean" instead.
  iris.groupby('class')[['petal length','sepal length']].aggregate(['min', np.mean, max])
C:\Users\meddi\AppData\Local\Temp\ipykernel_24152\1562241556.py:1: FutureWarning: The provided callable <built-in function max> is currently using SeriesGroupBy.max. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "max" instead.
  iris.groupby('class')[['petal length','sepal length']].aggregate(['min', np.mean, max])


petal length             sepal length            
                         min   mean  max          min   mean  max
class                                                            
Iris-setosa              1.0  1.464  1.9          4.3  5.006  5.8
Iris-versicolor          3.0  4.260  5.1          4.9  5.936  7.0
Iris-virginica           4.5  5.552  6.9          4.9  6.588  7.9

In [38]:
# This syntax will return the same result:

iris.groupby('class')[['petal length', 'sepal length']].aggregate(['min', 'mean', 'max'])

petal length             sepal length            
                         min   mean  max          min   mean  max
class                                                            
Iris-setosa              1.0  1.464  1.9          4.3  5.006  5.8
Iris-versicolor          3.0  4.260  5.1          4.9  5.936  7.0
Iris-virginica           4.5  5.552  6.9          4.9  6.588  7.9

# Grouping Multi-Index DataFrame

DataFrames can be split / grouped by multiple indexes. Let's use a simple DataFrame with abstract index columns and random data for this exercise, just to demonstrate the concept. Later in this module we will apply these concepts to the 311 New York dataset.

In [41]:
# Creating sample DataFrame to demonstrate the concepts
import numpy as np

df = pd.DataFrame({'A' : ['foo', 'bar', 'foo', 'bar',
                          'foo', 'bar', 'foo', 'foo'],
                   'B' : ['one', 'one', 'two', 'three',
                          'two', 'two', 'one', 'three'],
                   'C' : np.random.randn(8),
                   'D' : np.random.randn(8)})

df

A      B         C         D
0  foo    one  0.846447 -0.536967
1  bar    one  0.842366 -1.426950
2  foo    two  0.859428  0.465420
3  bar  three -0.979027 -0.303423
4  foo    two  1.547825  1.530492
5  bar    two  1.197933 -0.251896
6  foo    one  0.840301 -1.088913
7  foo  three  1.352814  0.063664

In [43]:
# We can use columns A and B as keys and split/group the DataFrame df by both keys:
grouped_df = df.groupby(['A', 'B'])

grouped_df.groups

# Within the groups with the key 'foo', 'one' comes before 'three' which comes before 'two' alphabetically.

{('bar', 'one'): [1], ('bar', 'three'): [3], ('bar', 'two'): [5], ('foo', 'one'): [0, 6], ('foo', 'three'): [7], ('foo', 'two'): [2, 4]}

In [74]:
# my suggested code

for i in df.groupby(['A', 'B']):
    print(i)

(('bar', 'one'),                 C        D
A   B                     
bar one  0.842366 -1.42695)
(('bar', 'three'),                   C         D
A   B                        
bar three -0.979027 -0.303423)
(('bar', 'two'),                 C         D
A   B                      
bar two  1.197933 -0.251896)
(('foo', 'one'),                 C         D
A   B                      
foo one  0.846447 -0.536967
    one  0.840301 -1.088913)
(('foo', 'three'),                   C         D
A   B                        
foo three  1.352814  0.063664)
(('foo', 'two'),                 C         D
A   B                      
foo two  0.859428  0.465420
    two  1.547825  1.530492)


In [85]:
# We can iterate over groups and print the group name and group data as follows:
for i, group  in df.groupby(['A', 'B']):
    print(i)
    print(group) # qn ?

('bar', 'one')
                C        D
A   B                     
bar one  0.842366 -1.42695
('bar', 'three')
                  C         D
A   B                        
bar three -0.979027 -0.303423
('bar', 'two')
                C         D
A   B                      
bar two  1.197933 -0.251896
('foo', 'one')
                C         D
A   B                      
foo one  0.846447 -0.536967
    one  0.840301 -1.088913
('foo', 'three')
                  C         D
A   B                        
foo three  1.352814  0.063664
('foo', 'two')
                C         D
A   B                      
foo two  0.859428  0.465420
    two  1.547825  1.530492


In [84]:
# We can iterate over groups and print the group name and group data as follows:
for (key1, key2), group in df.groupby(['A', 'B']):
    print((key1, key2))
    print(group) # qn ?

('bar', 'one')
                C        D
A   B                     
bar one  0.842366 -1.42695
('bar', 'three')
                  C         D
A   B                        
bar three -0.979027 -0.303423
('bar', 'two')
                C         D
A   B                      
bar two  1.197933 -0.251896
('foo', 'one')
                C         D
A   B                      
foo one  0.846447 -0.536967
    one  0.840301 -1.088913
('foo', 'three')
                  C         D
A   B                        
foo three  1.352814  0.063664
('foo', 'two')
                C         D
A   B                      
foo two  0.859428  0.465420
    two  1.547825  1.530492


In [90]:
grouped_df.groups

{('bar', 'one'): [1], ('bar', 'three'): [3], ('bar', 'two'): [5], ('foo', 'one'): [0, 6], ('foo', 'three'): [7], ('foo', 'two'): [2, 4]}

In [58]:
# And now we can calculate the means of the grouped data:
grouped_df.mean()

C         D
A   B                        
bar one    0.842366 -1.426950
    three -0.979027 -0.303423
    two    1.197933 -0.251896
foo one    0.843374 -0.812940
    three  1.352814  0.063664
    two    1.203627  0.997956

In [59]:
# Other methods are also supported, for example, max() or min(), or count(), etc.:
grouped_df.count()

C  D
A   B          
bar one    1  1
    three  1  1
    two    1  1
foo one    2  2
    three  1  1
    two    2  2

If the DataFrame has a hierarchical index, we can group by one of the levels of the hierarchy. In order to demonstrate this scenario, we will update the df DataFrame by setting the index to be a two-level MultiIndex:

In [60]:
df.set_index(['A', 'B'], inplace=True)
df

C         D
A   B                        
foo one    0.846447 -0.536967
bar one    0.842366 -1.426950
foo two    0.859428  0.465420
bar three -0.979027 -0.303423
foo two    1.547825  1.530492
bar two    1.197933 -0.251896
foo one    0.840301 -1.088913
    three  1.352814  0.063664

In [62]:
# to confirm that we have a DataFrame with MultiIndex
df.index

MultiIndex([('foo',   'one'),
            ('bar',   'one'),
            ('foo',   'two'),
            ('bar', 'three'),
            ('foo',   'two'),
            ('bar',   'two'),
            ('foo',   'one'),
            ('foo', 'three')],
           names=['A', 'B'])

level : int, level name, or sequence of such, default None
    If the axis is a MultiIndex (hierarchical), group by a particular level or levels. Do not specify both by and level.

In [63]:
# Now we can group by one or both levels:
df.groupby(level=['A', 'B']).count()

C  D
A   B          
bar one    1  1
    three  1  1
    two    1  1
foo one    2  2
    three  1  1
    two    2  2

Selecting a row or column

In the example above, when we grouped the DataFrame by 2 keys and calculated the average values for each of the group, the resulting DataFrame is a MultiIndex object. Let's quickly review how we can operate with this data.

Here is the DataFrame we had:

In [64]:
df_means = grouped_df.mean()

df_means

C         D
A   B                        
bar one    0.842366 -1.426950
    three -0.979027 -0.303423
    two    1.197933 -0.251896
foo one    0.843374 -0.812940
    three  1.352814  0.063664
    two    1.203627  0.997956

In [65]:
df_means.index

MultiIndex([('bar',   'one'),
            ('bar', 'three'),
            ('bar',   'two'),
            ('foo',   'one'),
            ('foo', 'three'),
            ('foo',   'two')],
           names=['A', 'B'])

How do we access data in MultiIndex DataFrames? Let's review. If we need to select only one subgroup of data, for example, bar or C, we can do it as follows:

In [86]:
# Select column 'C'
df_means['C']

# When we select column 'C' , we get back a Series with the same MultiIndex as the original DataFrame.

A    B    
bar  one      0.842366
     three   -0.979027
     two      1.197933
foo  one      0.843374
     three    1.352814
     two      1.203627
Name: C, dtype: float64

In [87]:
df_means.loc['bar']

# When we select a group of rows with the 'bar' index, we get back a DataFrame which has a single-level index.

C         D
B                        
one    0.842366 -1.426950
three -0.979027 -0.303423
two    1.197933 -0.251896

# stack( ) and unstack( )

Pandas has two functions for reshaping the DataFrame and changing the index: stack() and unstack(). The stack() function "compresses" a level in the DataFrame's columns to produce either:

A Series, in the case of a simple column Index.
A DataFrame, in the case of MultiIndex columns.
If the columns have a MultiIndex, we can choose which level to stack. The stacked level becomes the new lowest level in a MultiIndex on the columns. 

Let's take the `DataFrame` `df_means` and demonstrate:

In [101]:
df_means

C         D
A   B                        
bar one    0.842366 -1.426950
    three -0.979027 -0.303423
    two    1.197933 -0.251896
foo one    0.843374 -0.812940
    three  1.352814  0.063664
    two    1.203627  0.997956

In [92]:
df_stacked = df_means.stack() # Stack the prescribed level(s) from columns to index.

df_stacked

A    B       
bar  one    C    0.842366
            D   -1.426950
     three  C   -0.979027
            D   -0.303423
     two    C    1.197933
            D   -0.251896
foo  one    C    0.843374
            D   -0.812940
     three  C    1.352814
            D    0.063664
     two    C    1.203627
            D    0.997956
dtype: float64

In [100]:
df_stacked.index

# The None value in the names parameter of the MultiIndex indicates that the level doesn't have a name assigned to it.

MultiIndex([('bar',   'one', 'C'),
            ('bar',   'one', 'D'),
            ('bar', 'three', 'C'),
            ('bar', 'three', 'D'),
            ('bar',   'two', 'C'),
            ('bar',   'two', 'D'),
            ('foo',   'one', 'C'),
            ('foo',   'one', 'D'),
            ('foo', 'three', 'C'),
            ('foo', 'three', 'D'),
            ('foo',   'two', 'C'),
            ('foo',   'two', 'D')],
           names=['A', 'B', None])